export { ScamDatabase } from './ScamDatabase'
export { LinkAnalyzer } from './LinkAnalyzer'
export { LinkScanner } from './LinkScanner'
export { ContentScanner } from './ai-detection'
export type { ScanContentInput } from './ai-detection'
export { WindowTrackerService } from './WindowTrackerService'
export { createWindowTracker } from './windowTracker'
export type { WindowTrackerSnapshot } from '../../shared/detection-types'
export { HoverDetector } from './HoverDetector'
export { OCREngine } from './ocrEngine'
export type { OCREngineResult, OCREngineOptions } from './ocrEngine'
export { ScamDetector } from './scamDetector'
export type { ScamDetectionResult, ScamDetectorOptions } from './scamDetector'
export { PermissionManager } from './PermissionManager'
export type { PermissionStatus } from '../shared/integration-types'
