export { EMAIL_APPLICATIONS, OUTLOOK_WEB_DOMAINS, OUTLOOK_DESKTOP_PROCESS_NAMES, isEmailApplication } from './EmailPatterns'
export type { WebmailApp, DesktopEmailApp, BrowserApp, EmailAppCheckResult } from './EmailPatterns'
export type { ActiveWindowInfo } from './ActiveWindowInfo'
export { ActiveWindowMonitor } from './ActiveWindowMonitor'
export { BrowserMonitor } from './BrowserMonitor'
export { EmailContentExtractor } from './EmailContentExtractor'
export { EmailDetector } from './EmailDetector'
export { parseGmailUrl, parseOutlookUrl, parseYahooUrl, parseProtonUrl, extractEmailContext } from './EmailUrlContext'
export type { WebmailSection, EmailUrlContext } from './EmailUrlContext'
export { DetectionScreenCapture } from './DetectionScreenCapture'
export type { CaptureBounds, PerformCaptureFn } from './DetectionScreenCapture'
export { EmailOCRProcessor } from './EmailOCRProcessor'
export type { EmailContent } from './EmailOCRProcessor'
export { preprocessForOCR, preprocessForOCRFirefox, cleanOCRText, extractTextRegion } from './imagePreprocess'
export type { Bounds } from './imagePreprocess'
export { OutlookDetector } from './OutlookDetector'
export type { OutlookContext, OutlookContextSection } from './OutlookDetector'
export { URLAreaOCR } from './URLAreaOCR'
export type { URLBarRegion } from './URLAreaOCR'
export { FullWidthOCRScanner } from './FullWidthOCRScanner'
export type { OCRResult } from './FullWidthOCRScanner'
export { EmailDetectionPipeline } from './EmailDetectionPipeline'
export type { EmailDetectionResult } from './EmailDetectionPipeline'
export { TieredDetectionSystem } from './TieredDetectionSystem'
export { PriorityManager } from './PriorityManager'
export type { DetectionPriority } from './PriorityManager'
export type { WindowInfo, Tier1Result, Tier2Result, Tier3Result } from './types'
